services:
  mongodb:
    image: mongo:7
    container_name: noshowiq-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: noshowiq-mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"

  app:
    build: .
    container_name: noshowiq-app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: noshow_iq
      MODEL_PATH: artifacts/model.joblib
    ports:
      - "8000:8000"

volumes:
  mongo_data:
